### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by PranavVS** [Richienb/audic#13]
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module.

**Comment by Richienb** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

<blockquote><img src="https://github.githubassets.com/images/modules/gists/gist-og-image.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c">Pure ESM package</a></strong></div><div>Pure ESM package. GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>
